# Generated by Django 5.1.5 on 2025-01-31 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_createaudiction_date_createaudiction_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createaudiction',
            name='image',
            field=models.ImageField(default='.images/default.jpg', upload_to='images/'),
        ),
    ]
