# Generated by Django 5.1.5 on 2025-01-31 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_createaudiction_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateAudiction',
            new_name='Auction',
        ),
    ]
