# Generated by Django 5.1.5 on 2025-02-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_listing_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='closed_auction',
            field=models.BooleanField(default=False),
        ),
    ]
