# Generated by Django 5.1.5 on 2025-02-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_listing_closed_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='closed_auction',
        ),
    ]
