# Generated by Django 5.1.5 on 2025-02-16 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_listing_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
    ]
