# Generated by Django 5.1.5 on 2025-02-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_remove_listing_image_listing_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, default='No description', null=True),
        ),
    ]
